#+TITLE: Shmill's Emacs Config
#+Author: TheShmill
#+Description: My config for emacs, heavily inspired by kickstart.emacs
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes
#+Startup: showeverything
#+OPTIONS: toc:2
* config tangle
Use org-tangle to convert this org file into an elisp file.
#+begin_src emacs-lisp
  (defun start/org-babel-tangle-file ()
    "Tangle config.org into init.el"
    (when (string-equal (file-name-directory (buffer-file-name))
			(expand-file-name user-emacs-directory))
      (let ((org-confirm-babel-evaluate nil))
	(org-babel-tangle))))
  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'start/org-babel-tangle-file)))
#+end_src
* custom.el
We don't want random customize junk to be in init.el, so we'll put it in custom.el
#+begin_src emacs-lisp
  (setq custom-file (concat user-emacs-directory "custom.el"))
  (when (file-exists-p custom-file)
    (load custom-file))
#+end_src
* Mac os meta key
I'd like to use command instead of option for meta.
#+begin_src emacs-lisp
  (setq mac-command-modifier 'meta
	mac-option-modifier nil)
#+end_src
* use-package
use-package is a nice library for configuring and installing packages
#+begin_src emacs-lisp
  (require 'use-package)
#+end_src
* MELPA
A bunch of extra libraries for emacs
#+begin_src emacs-lisp
  (require 'package)
  (add-to-list 'package-archives
	       '("melpa" . "https://melpa.org/packages/") t)
#+end_src
* Magit
Awesome wrapper around git
#+begin_src emacs-lisp
  (use-package magit
    :ensure t)  
#+end_src
* exec-shell-from-path
Mac OS doesn't set environment variables correctly for emacs. exec-path-from-shell package fixes this.
#+begin_src emacs-lisp
  (use-package exec-path-from-shell
    :ensure t
    :config (exec-path-from-shell-initialize))
#+end_src
* General emacs settings
random tweaks for emacs
#+begin_src emacs-lisp
  (use-package emacs
	:custom
	(menu-bar-mode t) ;; I actually like having this on
	(scroll-bar-mode nil)
	(tool-bar-mode nil)
	(electric-pair-mode t) ; match parens
	(global-auto-revert-mode t)
	(tab-width 4)
	(make-backup-files nil)
	(auto-save-default nil)
	;; hide commands that don't support the current mode
	(read-extended-command-predicate #'command-completion-default-include-p))
#+end_src
* diff-hl
Cute little colors on the side to show git status of files
#+begin_src emacs-lisp
  (use-package diff-hl
	:ensure t
	:config
	(global-diff-hl-mode)
	(add-hook 'magit-post-refresh-hook 'diff-hl-magit-post-refresh)
	)
#+end_src
* vterm
Really solid terminal, but I might try eshell later
#+begin_src emacs-lisp
  (use-package vterm
	:ensure t)
#+end_src
* PDF reading
Make the PDF viewing experience nicer
#+begin_src emacs-lisp
  (use-package pdf-tools
	:ensure t)

  (use-package pdf-view-restore
	:ensure t
	:after pdf-tools
	:config
	(add-hook 'pdf-view-mode-hook 'pdf-view-restore-mode)
	:custom
	(pdf-view-restore-filename (concat user-emacs-directory ".pdf-view-restore")))
#+end_src
* Vertico
Completion stuff for minibuffer thingies
#+begin_src emacs-lisp
  (use-package vertico
	:ensure t
	:init (vertico-mode))

  (use-package marginalia ; provide descriptions for vertico stuff
	:ensure t
	:init (marginalia-mode))
#+end_src
